# Generated by Django 6.0.3 on 2026-03-16 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listecourses',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='listes_partagees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listecourses',
            name='share_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True),
        ),
    ]
