# Generated by Django 6.0.3 on 2026-03-16 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_listecourses_membres_listecourses_share_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listecourses',
            name='share_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
