# Generated by Django 6.0.3 on 2026-03-16 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_listecourses_share_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listecourses',
            name='share_token',
        ),
        migrations.AddField(
            model_name='listecourses',
            name='share_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, unique=True, verbose_name='Code de partage'),
        ),
        migrations.AlterField(
            model_name='listecourses',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='listes_partagees', to=settings.AUTH_USER_MODEL, verbose_name='Autres personnes'),
        ),
    ]
